### PR TITLE
Apply figma design to requests page header

### LINKED ISSUE #126: [Admin] Move "Export" button to left, and change "Requests" page header
Make "Requests" page to look like in figma design

- Move page title above buttons
- Move "Export" button to the left
- Add a disabled "Import" button, for future use

https://www.figma.com/file/oCN3NSECKQnS4PWhZnWGCT/Dashboard_Voluntar.md_V2.0?node-id=565%3A188

### PR DESCRIPTION
**Pull request by erikaya**
Closes #126 

I added a new structure to _requests-list.component.html_ and its css so it can be equal to Figma.

I also added some icons to the app component icon list so it can be used on this page.

### CODE REVIEW

**Comment by erikaya** [comment]
Requests page header after applying figma definitions

The scope of this PR is limited to Requests page header

**Comment by erikaya** [comment]
Requests page header after applying figma rules

The scope of this PR is limited to the Request page **header** only

**Comment by erikaya** [comment]
@iamandrewluca What do you think of this?

**Review by unrevised6419 — APPROVED** [review]
Thanks @erikaya for the PR. I removed some styles, because they need to be applied globally.

**Pull request merged**
